version: 2
updates:
  # Docker base image updates for root Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 10

  # GitHub Actions workflow action updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 10
