services:
  aiagent:
    image: ghcr.io/yanchihuang/dev-ai-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-22}
    container_name: devaiagent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - NODE_VERSION=${NODE_VERSION:-22}
      - TZ=${TZ:-UTC}
    volumes:
      - ./workspace:/home/aiagent/workspace
      - ./config:/home/aiagent/config
      - ./config/gitconfig:/home/aiagent/.gitconfig
      - ./config/gemini:/home/aiagent/.gemini
      - ~/.ssh:/home/aiagent/.ssh:ro
      - projects:/home/aiagent/projects
    working_dir: /home/aiagent/workspace
    tty: true
    stdin_open: true
    networks:
      - aiagent-network

networks:
  aiagent-network:
    driver: bridge

volumes:
  projects:
